grammar test_mico;
prule: DATETIME*;

OPERATION: WHITESPACE* NUMBER  WHITESPACE* '*' WHITESPACE* NUMBER;
WHITESPACE : ' ' -> skip;
fragment NUMBER : [0-9]+;
CHAR : [a-z]|[A-z]|'_';
fragment WORD : CHAR+;
DIGIT: WHITESPACE* [0-9] WHITESPACE*;
TWODIGIT : DIGIT DIGIT;
DAY : WORD;
HOUR : TWODIGIT;
MINUTE : TWODIGIT;
SECOND : TWODIGIT;

TIME :  HOUR ':' MINUTE ':' SECOND ;
DATETIME : DAY ' ' TIME ';\n';
